platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

workspace 'AnalyticsKit'
xcodeproj 'AnalyticsKit'

pod 'Adjust'
pod 'Fabric'
pod 'Crashlytics'
pod 'Flurry-iOS-SDK';
pod 'GoogleAnalytics'
pod 'Localytics'
pod 'Mixpanel'
pod 'NewRelicAgent'
pod 'Parse'

