platform :ios, '8.0'

source 'git@bitbucket.org:cabosoft-mobile/cabopods-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'AnalyticsKit'
project 'AnalyticsKit'

use_frameworks!

target 'AnalyticsKit' do
	pod 'Adjust'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Flurry-iOS-SDK';
	pod 'GoogleAnalytics'
	pod 'Localytics'
	pod 'Mixpanel'
	pod 'NewRelicAgent'
	pod 'Parse'
end
